import * as schema from "./schema/index.js";

export { schema };
export * from "./schema/index.js";

export { createDb, selectDriver, type Db, type DbDriver, type Schema, type Tx } from "./client.js";
export {
  tenantScoped,
  tenantTables,
  assertTenantId,
  setTenantContext,
  setUserContext,
  DEFAULT_MEMBER_PREFERENCES,
  type MemberPreferences,
  type TenantDb,
  type TenantMemberships,
  type TenantQueries,
  type TenantTable,
  type TenantTx,
} from "./tenant.js";
export { createConversationStore } from "./conversation-store.js";
export {
  usage,
  getUsageCaps,
  parseIntEnv,
  utcWindows,
  DEFAULT_DAILY_TOKENS,
  DEFAULT_MONTHLY_CHECKS,
  type CapCheckResult,
  type CapHitInput,
  type CapReason,
  type RecordCheckInput,
  type UsageCaps,
} from "./usage.js";
export { createTenantForUser, findTenantForUser, getHouseholdName, type UserTenant } from "./tenants.js";
export { createMemoryBlobClient, createVercelBlobClient, type BlobClient } from "./blob.js";
export {
  ArtifactStoreUnavailableError,
  DEFAULT_ARTIFACT_RETENTION_DAYS,
  artifactBlobPath,
  artifactRetentionDays,
  createArtifactStore,
  type ArtifactMeta,
  type ArtifactStore,
  type ArtifactStoreOptions,
  type PutArtifactInput,
} from "./artifact-store.js";
export {
  generateLocalPart,
  inbound,
  inboundAddressFor,
  isInboundLocalPart,
  type InboundAddress,
  type InboundMessagePatch,
  type InboundMessageRow,
  type RecordMessageInput,
} from "./inbound.js";
export {
  InvalidCursorError,
  decodeVerdictCursor,
  encodeVerdictCursor,
  listMembers,
  saveVerdict,
  verdictQueries,
  type HouseholdMember,
  type SaveVerdictInput,
  type VerdictListOptions,
  type VerdictRow,
  type VerdictSummary,
} from "./verdicts.js";
export {
  DESKTOP_TOKEN_PREFIX,
  MAX_DESKTOP_TOKEN_NAME,
  MAX_DESKTOP_TOKENS_PER_USER,
  createDesktopToken,
  hashDesktopToken,
  isDesktopTokenFormat,
  listDesktopTokens,
  normalizeDesktopTokenName,
  resolveDesktopToken,
  revokeDesktopToken,
  type DesktopTokenPublic,
  type DesktopTokenRow,
  type ResolvedDesktopToken,
} from "./desktop-tokens.js";
export {
  DESKTOP_AUTH_POLL_INTERVAL_S,
  DESKTOP_AUTH_TTL_MS,
  DEVICE_CODE_PREFIX,
  MAX_DESKTOP_CLIENT_NAME,
  createDesktopAuthRequest,
  decideDesktopAuthRequest,
  generateUserCode,
  getDesktopAuthRequest,
  hashDeviceCode,
  isDeviceCodeFormat,
  mintDeviceCode,
  normalizeClientName,
  normalizeUserCode,
  redeemDesktopAuthRequest,
  type DesktopAuthApprover,
  type DesktopAuthDecision,
  type DesktopAuthRedemption,
  type DesktopAuthRequestPublic,
} from "./desktop-auth.js";
export {
  HOUSEHOLD_INVITE_TTL_MS,
  INVITE_SECRET_PREFIX,
  MAX_HOUSEHOLD_SIZE,
  acceptHouseholdInvite,
  createHouseholdInvite,
  hashInviteSecret,
  inviteSecretPrefix,
  isInviteSecretFormat,
  leaveHousehold,
  listPendingHouseholdInvites,
  mintInviteSecret,
  normalizeInviteEmail,
  previewHouseholdInvite,
  removeHouseholdMember,
  revokeHouseholdInvite,
  rotateHouseholdInvite,
  type AcceptInviteError,
  type AcceptInviteResult,
  type CreateInviteError,
  type DetachResult,
  type HouseholdInvitePublic,
  type InvitePreview,
} from "./household.js";
export {
  ALERT_BODY_MAX,
  ALERT_TITLE_MAX,
  acknowledgeAlert,
  acknowledgeAllAlerts,
  countAlertEmailsSince,
  countOpenAlerts,
  createAlert,
  getAlert,
  getAlertEmailThreshold,
  listAlertOwners,
  listAlerts,
  markAlertEmail,
  purgeOldAlerts,
  setAlertEmailThreshold,
  type AlertListItem,
  type AlertOwner,
  type AlertRow,
  type CreateAlertInput,
} from "./alerts.js";
// runMigrations lives in the "@neo/db/migrate" subpath so app bundles never see the migrations folder.
export type { ConversationStore, MessageParam } from "@neo/core";
