import * as schema from "./schema/index.js";

export { schema };
export * from "./schema/index.js";

export { createDb, selectDriver, type Db, type DbDriver, type Schema, type Tx } from "./client.js";
export {
  tenantScoped,
  tenantTables,
  assertTenantId,
  setTenantContext,
  setUserContext,
  DEFAULT_MEMBER_PREFERENCES,
  type MemberPreferences,
  type TenantDb,
  type TenantMemberships,
  type TenantQueries,
  type TenantTable,
  type TenantTx,
} from "./tenant.js";
export { createConversationStore } from "./conversation-store.js";
export {
  usage,
  getUsageCaps,
  parseIntEnv,
  utcWindows,
  DEFAULT_DAILY_TOKENS,
  DEFAULT_MONTHLY_CHECKS,
  type CapCheckResult,
  type CapHitInput,
  type CapReason,
  type RecordCheckInput,
  type UsageCaps,
} from "./usage.js";
export { createTenantForUser, findTenantForUser, getHouseholdName, type UserTenant } from "./tenants.js";
export { createMemoryBlobClient, createVercelBlobClient, type BlobClient } from "./blob.js";
export {
  ArtifactStoreUnavailableError,
  DEFAULT_ARTIFACT_RETENTION_DAYS,
  artifactBlobPath,
  artifactRetentionDays,
  createArtifactStore,
  type ArtifactMeta,
  type ArtifactStore,
  type ArtifactStoreOptions,
  type PutArtifactInput,
} from "./artifact-store.js";
export {
  generateLocalPart,
  inbound,
  inboundAddressFor,
  isInboundLocalPart,
  type InboundAddress,
  type InboundMessagePatch,
  type InboundMessageRow,
  type RecordMessageInput,
} from "./inbound.js";
export {
  InvalidCursorError,
  decodeVerdictCursor,
  encodeVerdictCursor,
  listMembers,
  saveVerdict,
  verdictQueries,
  type HouseholdMember,
  type SaveVerdictInput,
  type VerdictListOptions,
  type VerdictRow,
  type VerdictSummary,
} from "./verdicts.js";
export {
  DESKTOP_TOKEN_PREFIX,
  MAX_DESKTOP_TOKEN_NAME,
  MAX_DESKTOP_TOKENS_PER_USER,
  createDesktopToken,
  hashDesktopToken,
  insertDeviceToken,
  isDesktopTokenFormat,
  listDesktopTokens,
  normalizeDesktopTokenName,
  resolveDesktopToken,
  revokeDesktopToken,
  type DesktopTokenPublic,
  type DesktopTokenRow,
  type ResolvedDesktopToken,
} from "./desktop-tokens.js";
export {
  DESKTOP_AUTH_POLL_INTERVAL_S,
  DESKTOP_AUTH_TTL_MS,
  DEVICE_CODE_PREFIX,
  MAX_DESKTOP_CLIENT_NAME,
  createDesktopAuthRequest,
  decideDesktopAuthRequest,
  generateUserCode,
  getDesktopAuthRequest,
  hashDeviceCode,
  isDeviceCodeFormat,
  mintDeviceCode,
  normalizeClientName,
  normalizeUserCode,
  redeemDesktopAuthRequest,
  type DesktopAuthApprover,
  type DesktopAuthDecision,
  type DesktopAuthRedemption,
  type DesktopAuthRequestPublic,
} from "./desktop-auth.js";
export {
  DEVICE_OFFLINE_AFTER_MS,
  ENROLLMENT_CODE_TTL_MS,
  MAX_DEVICES_PER_HOUSEHOLD,
  MAX_DEVICE_CLIENT_VERSION,
  MAX_DEVICE_NAME,
  MAX_PENDING_ENROLLMENT_CODES,
  createEnrollmentCode,
  enrollSelfDevice,
  getDevice,
  hashEnrollmentCode,
  listDevices,
  listPendingEnrollmentCodes,
  listStaleDevices,
  lookupDeviceTenant,
  markDeviceOfflineAlerted,
  mintEnrollmentCode,
  normalizeDeviceInput,
  normalizeDeviceName,
  normalizeEnrollmentCode,
  previewEnrollmentCode,
  purgeOldDevices,
  recordHeartbeat,
  redeemEnrollmentCode,
  renameDevice,
  revokeDevice,
  revokeEnrollmentCode,
  type DeviceInput,
  type DevicePublic,
  type EnrollSelfDeviceResult,
  type EnrollmentCodePreview,
  type EnrollmentCodePublic,
  type RedeemEnrollmentCodeResult,
} from "./devices.js";
export {
  HOUSEHOLD_INVITE_TTL_MS,
  INVITE_SECRET_PREFIX,
  MAX_HOUSEHOLD_SIZE,
  acceptHouseholdInvite,
  createHouseholdInvite,
  hashInviteSecret,
  inviteSecretPrefix,
  isInviteSecretFormat,
  leaveHousehold,
  listPendingHouseholdInvites,
  mintInviteSecret,
  normalizeInviteEmail,
  previewHouseholdInvite,
  removeHouseholdMember,
  revokeHouseholdInvite,
  rotateHouseholdInvite,
  type AcceptInviteError,
  type AcceptInviteResult,
  type CreateInviteError,
  type DetachResult,
  type HouseholdInvitePublic,
  type InvitePreview,
} from "./household.js";
export {
  ALERT_BODY_MAX,
  ALERT_TITLE_MAX,
  acknowledgeAlert,
  acknowledgeAllAlerts,
  countAlertEmailsSince,
  countOpenAlerts,
  createAlert,
  getAlert,
  getAlertEmailThreshold,
  listAlertOwners,
  listAlerts,
  markAlertEmail,
  purgeOldAlerts,
  setAlertEmailThreshold,
  type AlertListItem,
  type AlertOwner,
  type AlertRow,
  type CreateAlertInput,
} from "./alerts.js";
export {
  PostgresReputationCache,
  SIGNAL_OUTCOMES,
  countDeviceSignalsSince,
  getDeviceSignal,
  insertDeviceSignal,
  listDeviceSignalsByClientIds,
  listExpectedTools,
  listRecentUserSignals,
  purgeExpiredReputationCache,
  purgeOldDeviceSignals,
  setExpectedTools,
  updateDeviceSignal,
  type DeviceSignalRow,
  type ExpectedToolRow,
  type InsertDeviceSignalInput,
  type SetExpectedToolsInput,
  type UpdateDeviceSignalPatch,
} from "./signals.js";
// runMigrations lives in the "@neo/db/migrate" subpath so app bundles never see the migrations folder.
export type { ConversationStore, MessageParam } from "@neo/core";

export { weeklyDigest, type DigestDelivery, type DigestClaim, type DigestClaimResult } from "./weekly-digest.js";
export {
  breachMonitoring,
  type AddressRow,
  type AddressRow as MonitoredAddressRow,
  type ObservationRow as BreachObservationRow,
  type BreachObservationInput,
  type CheckStatus as BreachCheckStatus,
  type RequestVerificationResult,
} from "./breach-monitoring.js";
export {
  accountHardening,
  type AccountHardeningAnswer,
  type AccountHardeningEvidenceId,
  type AccountHardeningItemId,
  type AccountHardeningState,
  type AccountHardeningVersion,
} from "./account-hardening.js";
export type { SigninEvent, SigninEventInput, SigninEventSource, TenantSigninEvents } from "./signin-events.js";
export {
  outlookScheduler,
  type OutlookConnector,
  type OutlookConnectorSummary,
  type OutlookFindingInput,
  type OutlookOAuthState,
  type OutlookRuleFinding,
  type TenantOutlookConnectors,
  type TenantOutlookOAuthStates,
  type TenantOutlookRuleFindings,
  type TenantOutlookSeenMessages,
} from "./outlook.js";
export type { OutlookConnectorStatus, OutlookFindingAction, OutlookFindingState } from "./schema/outlook.js";
